services:
  app:
    build: app/
    environment:
      - GIT_REPO_URL=ssh://git@git.example.com/repo.git
    volumes:
      - ~/.ssh:/root/.ssh
  nginx:    
    build: nginx/
    ports:
      - "80:80"
