services:
  app:
    build: app/
    environment:
      - GIT_REPO_URL=ssh://git@platform.sunet.se:22022/khn/configtest.git
    volumes:
      - ~/.ssh:/root/.ssh
  nginx:    
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/zoomie.sunet.se/:/ssl
