# Compose file
services:
  app:
    build: app/
    volumes:
      - ./repo:/repo
  nginx:    
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/zoomie.sunet.se/:/ssl
