# Compose file
services:
  app:
    build: app/
    environment:
      - GIT_REPO_URL=
    volumes:
      - ~/.ssh:/root/.ssh
  nginx:    
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/host.name.com/:/ssl
